# Site settings
title: Robin's personal website

description: >- # this means to ignore newlines until "baseurl:"
  Mechatronics Engineering Graduate, Electronics Enthusiast, and amateur Software Developer. 
domain: robinli.xyz
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robinli.xyz" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings


# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
